import type {Metadata} from "next";

import "./globals.css";

// primereact
import "primereact/resources/themes/tailwind-light/theme.css";
import "primereact/resources/primereact.min.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html
      lang="en"
      style={{
        fontFamily: "Urbanist, sans-serif",
        scrollBehavior: "smooth",
      }}
    >
      <body>{children}</body>
    </html>
  );
}
